const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
const context={window:{},structuredClone,crypto:require('node:crypto').webcrypto};
vm.runInNewContext(fs.readFileSync('p/chogeumbi/model.js','utf8'),context);
const M=context.window.CHOGEUMBI_MODEL;
const d=M.normalize({schedules:[],upbo:[{id:'old',nickname:'테스터',viewerId:'user',item:'방셀',season:'시즌 1',quantity:2,status:'대기'}]});
assert.equal(d.members.length,1);assert.equal(d.taskTypes.length,1);
M.assign(d,d.members[0].id,d.taskTypes[0].id,'시즌 1',3);
assert.equal(d.upbo.length,1);assert.equal(d.upbo[0].quantity,5);assert.equal(d.upbo[0].allocated,5);
M.finish(d,'old',2);assert.equal(d.upbo[0].quantity,3);assert.equal(d.upbo[0].completed,2);assert.equal(d.upbo[0].allocated,5);
assert.throws(()=>M.finish(d,'old',4));assert.equal(d.upbo[0].quantity,3);
M.assign(d,d.members[0].id,d.taskTypes[0].id,'시즌 2',1);assert.equal(d.upbo.length,2);
M.manual(d,{id:'new',nickname:'테스터',viewerId:'user',item:'방셀',season:'시즌 1',quantity:2,status:'대기',sample:false});
assert.equal(d.upbo.length,2);assert.equal(d.upbo[0].quantity,5);assert.equal(d.upbo[0].completed,2);
M.finish(d,'old',5);assert.equal(d.upbo[0].status,'전달 완료');assert.equal(d.upbo[0].quantity,0);
M.assign(d,d.members[0].id,d.taskTypes[0].id,'시즌 1',1);assert.equal(d.upbo[0].status,'대기');
assert.throws(()=>M.assign(d,d.members[0].id,d.taskTypes[0].id,'시즌 1',1.5));
const round=M.normalize(JSON.parse(JSON.stringify(d)));assert.equal(round.upbo[0].completed,7);assert.equal(round.upbo[0].allocated,8);
assert.equal(round.history.length,6);
console.log('PASS: migration, accumulation, completion, overspend rejection, season isolation, manual merge, reopen, persistence');
